title: zzz
frequency: 1
dirfilter:
- tmp
- .git
- .github
- public
- scripts
- vendor
- custom
- data
- logs
- pb
- assets
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go generate internal/assets/conf/conf.go
  - protoc --go_out=plugins=grpc:./pb ./pb/repo.proto
  after:
  - ./facegit-rpc run &
  exit:
  - ps -ef|grep 'facegit-rpc run'| grep -v grep
  - ps -ef|grep 'facegit-rpc run'| grep -v grep | awk '{print $2}' | xargs kill -9 
link: https://github.com/midoks/zzz
