title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- assets
ext:
- go
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - go generate internal/assets/conf/conf.go
  after:
  - ps -ef|grep 'facegit-rpc run'| grep -v grep | awk '{print $2}' | xargs kill -9  && ./facegit-rpc run &
link: https://github.com/midoks/zzz
